typography_spectrum: 0.9666884746402502
color:
  brandStrength: 0.3312989918049425
  lightness: 0.5838175842072815
  saturation: 0.303149557672441
  rhythmicContrast: 0.8895382271148264
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
layout_spectrum: 0.670940964249894
author:
  name: Walter Harmer
  email: Chad.Harmer@yahoo.ca
  url: HarmerWealth.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a82c8663-e767-4654-be71-0ac057920b72.png
name: Harmer Wealth
navigation:
  - name: About Us
    id: 78d4c8fa-b709-4c46-9557-dd836bee6870
    type: content
  - name: What We Think
    id: d092392a-0557-4115-90ca-df4511f7ef93
    type: content
  - name: What We Do
    id: 306c07d9-b062-4251-b5bb-f0f7a053db85
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/71fdd2ca-f5ba-4bf8-8c8b-c38329f59a34.png
title: Harmer Wealth Management
description: 'Your Wealth: Discover the possibility'
