layout_spectrum: 0.9688733094371855
typography_spectrum: 0.911807797383517
color:
  brandStrength: 0.09626282937824726
  lightness: 0.6823748101014644
  saturation: 0.2125141874421388
  rhythmicContrast: 0.7277985450346023
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#5B5B5B'
    - '#AAAAAA'
    - '#FED77C'
name: Harmer Wealth
