typography_spectrum: 0.911807797383517
color:
  brandStrength: 0.09626282937824726
  lightness: 0.6823748101014644
  saturation: 0.2125141874421388
  rhythmicContrast: 0.7277985450346023
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.9688733094371855
author:
  name: Chad Harmer
  email: Chad.Harmer@yahoo.ca
  url: HarmerWealth.com
name: Harmer Wealth
title: Harmer Wealth Management
description: 'Your Wealth: Discover the possibility'
