typography_spectrum: 0.8818396877031773
color:
  brandStrength: 0.8441960117779672
  lightness: 0.040955410804599524
  saturation: 0.643511259695515
  rhythmicContrast: 0.47693067882210016
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
layout_spectrum: 0.8517362121492624
author:
  name: Chad Harmer
  email: Chad.Harmer@yahoo.ca
  url: HarmerWealth.com
name: Harmer Wealth
title: Harmer Wealth Management
description: 'Your Wealth: Discover the possibility'
